# Generated by Django 5.2.1 on 2025-05-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = []
