# Generated by Django 5.2.1 on 2025-05-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_auto_20250508_1934"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
