# Generated by Django 5.2.1 on 2025-05-20 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="reason_suppressed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("offensive", "Offensive Content"),
                    ("spam", "Spam"),
                    ("misinformation", "Misinformation"),
                    ("hate_speech", "Hate Speech"),
                    ("harassment", "Harassment"),
                    ("privacy", "Privacy Violation"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="reason_suppressed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("offensive", "Offensive Content"),
                    ("spam", "Spam"),
                    ("misinformation", "Misinformation"),
                    ("hate_speech", "Hate Speech"),
                    ("harassment", "Harassment"),
                    ("privacy", "Privacy Violation"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="app.user",
                    ),
                ),
            ],
        ),
    ]
